name: Build library

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Get submodules
        run: git submodule update --init --recursive

      - name: Build
        uses: threeal/cmake-action@v2.0.0
